# Generated by Django 5.0.3 on 2024-03-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='id',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
