# Generated by Django 5.0.3 on 2024-03-17 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='dt_nascimento',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value='1900-01-01')], verbose_name='Data de nascimento'),
        ),
    ]
