# Generated by Django 5.0.3 on 2024-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pessoa_dt_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='dt_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
    ]
